export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const STOP_PRODUCT_LOADING = "STOP_PRODUCT_LOADING";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";
